export default {
    GET_ALL_ENTERPRISES: "GET_ALL_ENTERPRISES",
    GET_ALL_ENTERPRISES_REQUEST: "GET_ALL_ENTERPRISES_REQUEST",
    GET_ALL_ENTERPRISES_RESPONSE: "GET_ALL_ENTERPRISES_RESPONSE",
    GET_ALL_ENTERPRISES_ERRORS: "GET_ALL_ENTERPRISES_ERRORS",

    GET_ALL_USER_ENTERPRISES: "GET_ALL_USER_ENTERPRISES",
    GET_ALL_USER_ENTERPRISES_REQUEST: "GET_ALL_USER_ENTERPRISES_REQUEST",
    GET_ALL_USER_ENTERPRISES_RESPONSE: "GET_ALL_USER_ENTERPRISES_RESPONSE",
    GET_ALL_USER_ENTERPRISES_ERRORS: "GET_ALL_USER_ENTERPRISES_ERRORS",

    CREATE_ENTERPRISE: "CREATE_ENTERPRISE",
    CREATE_ENTERPRISE_REQUEST: "CREATE_ENTERPRISE_REQUEST",
    CREATE_ENTERPRISE_RESPONSE: "CREATE_ENTERPRISE_RESPONSE",
    CREATE_ENTERPRISE_ERROR: "CREATE_ENTERPRISE_ERROR",

    GET_ALL_ENTERPRISE_STATUS: "GET_ALL_ENTERPRISE_STATUS",
    GET_ALL_ENTERPRISE_STATUS_REQUEST: "GET_ALL_ENTERPRISE_STATUS_REQUEST",
    GET_ALL_ENTERPRISE_STATUS_RESPONSE: "GET_ALL_ENTERPRISE_STATUS_RESPONSE",
    GET_ALL_ENTERPRISE_STATUS_ERRORS: "GET_ALL_ENTERPRISE_STATUS_ERRORS",

    GET_ALL_INDUSTRY: "GET_ALL_INDUSTRY",
    GET_ALL_INDUSTRY_REQUEST: "GET_ALL_INDUSTRY_REQUEST",
    GET_ALL_INDUSTRY_RESPONSE: "GET_ALL_INDUSTRY_RESPONSE",
    GET_ALL_INDUSTRY_ERRORS: "GET_ALL_INDUSTRY_ERRORS",

    GET_ALL_CORPORATION: "GET_ALL_CORPORATION",
    GET_ALL_CORPORATION_REQUEST: "GET_ALL_CORPORATION_REQUEST",
    GET_ALL_CORPORATION_RESPONSE: "GET_ALL_CORPORATION_RESPONSE",
    GET_ALL_CORPORATION_ERRORS: "GET_ALL_CORPORATION_ERRORS",

    GET_CURRENT_USER: "GET_CURRENT_USER",
    LOGIN: "LOGIN",
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_RESPONSE: "LOGIN_RESPONSE",
    LOGIN_ERRORS: "LOGIN_ERRORS",

    IS_MODAL_OPEN: "IS_MODAL_OPEN",
}